### ISSUE TITLE
Allure themes - wondeful, with some minor issues!

### ISSUE THREAD

**Issue by 6-AND-9** [JadeVane/Allure#3]
Hi there.

First, please let me express my deepest appreciation for these themes. They look amazing, and I'm looking forward to using them in the long term. I will probably make a donation today as well.

Now, let me turn to some issues I've noticed, and best to do this by using screenshots.

Relationship maps:
![image](https://user-images.githubusercontent.com/51234066/117968948-0ee64300-b327-11eb-895a-d7a5ce566983.png)

As you can see, the nodes on the graph are white, while the text inside is light-gray. This makes them almost impossible to read. Is this an issue with Allure theme itself, or with something else? I'd appreciate your input and maybe some guidance on how to modify the background and text colour of nodes in the theme.

Diacritic signs in Cyrillic:
![image](https://user-images.githubusercontent.com/51234066/117969232-73a19d80-b327-11eb-8845-c5773fe0fe2b.png)
As you can see the diacritic signs (the apostrophe) on Cyrillic letters that have them is weirdly moved to the right, so it turns out as if the letter following has such a sign (when it doesn't).
What's written there should be looking like this in original:

Ќе 
ѝ 
сѐ
Ѓумбир

Again, I don't know if this is a problem with the theme or with the fact that I had another theme before Allure (but I reset the UI after applying Allure-dark). Again, any assistance would be greatly appreciated, since I freakin' love love love your theme.

- A

**Comment by JadeVane** [comment]
Hi, thanks for your appreciation.

In fact, the current version of Allure does not adapt to all functions for the reason that Allure actually changes trilium so deep that every subtle place needs to be adapted, but there are many functions that I don’t use when I work on trilium, so I didn’t adapt to this either. I'm sorry for everyone if this troubles you.

I have adapted the relationship maps on the latest version, you can try the effect here
Macedonian

**Comment by JadeVane** [comment]
Hi, thanks for your appreciation.

In fact, the current version of Allure does not adapt to all functions for the reason that Allure actually changes trilium so deep that every subtle place needs to be adapted, but there are many functions that I don’t use when I work on trilium, so I didn’t adapt to this either. I'm sorry for everyone if this troubles you.

I have adapted the relationship maps on the latest version, you can try the effect here:
Macedonian

**Comment by JadeVane** [comment]
Hi,

thanks for your appreciation.

In fact, the current version of Allure does not adapt to all functions on the Trilium for the reason that Allure actually changes Trilium so deep that every subtle place needs to be adapted, but there are many functions that I don’t use when I work on Trilium, so I didn’t adapt to this either. I'm sorry for everyone if this troubles you.

I have adapted the relationship maps on the latest version, just try it yourself: [Allure-nignt](https://github.com/JadeVane/Allure/blob/main/Allure-night.css)

At the same time, I'm not using Macedonian *(Hope I didn’t guess wrong)* , so I'm not sure if the fix will take effect this time, maybe you can give me some feedback after trying the latest version

**Comment by andrejdam** [comment]
A very weird thing happened now. Went to the new version, deleted the old one, made a new CSS note and pasted the contents. Now the theme simply doesn't work, even though I select it into Menu -> options, and I to CTRL + R. The simple white theme remains no matter how many times I reset Trilium.

![image](https://user-images.githubusercontent.com/51234066/118123041-f4c66680-b3f3-11eb-8a39-9b9e615c57ac.png)


I assume the issue is with this: Do NOT keep more than one version of css style to trilium, or the styles of several css style will affect each other and cause unexpected errors

So for that reason I deleted all other CSS notes and left only Allure-night. But it still doesn't work. Do you have an idea how I can fix this?

If I can get to work I can give you feedback regarding Cyrillic letters and the relation map.

**Comment by JadeVane** [comment]
@6-AND-9 This is my fault, I got the theme name wrong, the error has been fixed, just try again.

**Comment by 6-AND-9** [comment]
@JadeVane thanks, that fixed it. I can use the theme now. The Cyrillic issue remains the same, however. Hope it'll be fixed in some future iteration because your theme is awesome.

**Comment by JadeVane** [comment]
I'm sorry to reply you so late, because I have been traveling for a while.

Try to **DELETE** the Allure theme note you add before, and **CREATE** a new note follow the steps:

1. create a new note in trilium (of type CSS) named Allure-night
1. copy the content of [Allure-nigit](https://github.com/JadeVane/Allure/blob/main/Allure-night.css) and paste it into the new note created above
1. add `#appTheme` attribute to the note
1. go to `Menu` > `Options`, and select `Allure-night` as your new theme
1. Press `F5` or `Ctrl + R` to reload the page

You should be able to get this if you follow the correct steps to set the theme

![image](https://user-images.githubusercontent.com/34258753/118909506-b5e56300-b955-11eb-8609-e16482ca9b6b.png)
